### PR TITLE
Optimize json

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Part of #84
 - Parse json char by char rather than excessive regex checks
 - Only parse top level of objects and arrays
 - Lower level objects and arrays are parsed at runtime (JIT) when requested

Extremely efficient, processes in < 700ms rather than running out of memory (current behavior).

[WF-3223439976](https://github.com/KatsuteDev/OneMTA/actions/runs/3223439976)

#### Release Notes

* Increase parsing speed
* Parse partials rather than full json

### CODE REVIEW

**Comment by Katsute** [comment]
Make JsonObject get run the supplier then set that as the new get value

**Comment by Katsute** [comment]
~~Use findEndToken on string~~

Causes unnecessary overhead, already iterating through string, no need to check ahead.

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `upgrade-json@f3dfe30`

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `upgrade-json@f3dfe30`

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `upgrade-json@f3dfe30`

**Comment by Katsute** [comment]
@mashiro-san approve this pull

**Review by ghost — APPROVED** [review]
@Katsute I have approved this pull request

**Pull request merged**
