### PR TITLE
Use GTFS bus feed

### LINKED ISSUE #84: Use all bus data
### Feature

Anytime a bus is requested:

1. Check the cache
2. Pull data for **all** busses
3. Parse
4. Fulfill the request

### Reason

Current implementation runs a new request for every bus which is not efficient for enterprise. Requesting all busses then parsing is more efficient when submitting multiple requests.

### LINKED ISSUE #100: Use GTFS bus feeds
### Feature

Use GTFS feeds for bus rather than json

<http://bt.mta.info/wiki/Developers/GTFSRt>

### Reason

GTFS is far more efficient than raw json requests.

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Add GTFS bus feed
 - Store token headers inside service provider
 - Optimize map usage
 - Remove redundant attribute classes
 - Remove redundant GTFS classes
 - Remove redundant reference classes
 - Optimize feed entity
 - Optimize alert feed entity
 - Remove json + unused regex count
 - Add missing variables
 - Rename similar methods

[WF-3864033213](https://github.com/KatsuteDev/OneMTA/actions/runs/3864033213)

|[Bottom 🔽](#issue-comment-box)|
|---|

#### Release Notes

<h3 align="center">🛑 This major update includes breaking changes 🛑</h3>

This update drops the SIRI bus API in favor of the GTFS bus API. This update is most likely **not compatible** with previous versions of the bus API; all other modes should still be compatible with this update.

 * Removed `Json` and `JsonSyntaxException`
 * Removed `RailroadStop`
 * Removed `RailroadTripStop`
 * Replaced merged GTFS types into transit types
 * Optimizations to request headers
 * Optimizations to token usage
 * Optimizations to vehicle feeds
 * Optimizations to vehicle requests
 * Optimizations to alert requests

#### Attributes

Inlined several attributes and removed respective interfaces:

 * Removed `Bearing`
 * Condensed `RouteReference`, `StopReference`, `TripReference`, and `VehiclesReference` into a single `Reference` class
 * Removed `RouteDescription`
 * Removed `RouteShortName`

#### Alerts

 * Added created time
 * Added updated time
 * Removed alert effect
 * Added alert type

#### Bus

Dropped SIRI API in favor of GTFS API.

##### Stop

 * Removed origin stop
 * Removed destination
 * Removed progress rate
 * Removed progress status
 * Removed aimed arrival time
 * Removed expected departure time

##### Vehicle

 * Added passenger count
 * Removed arrival proximity
 * Removed stop distance

##### Trip

 * Added stop sequence
 * Added delay

##### Vehicle

 * Added assigned indicator
 * Added rerouted indicator
 * Added skip stop indicator
 * Added turn train indicator
 * Added stop sequence

##### Trip

 * Added trip stop sequence
 * Added trip stop schedule relationship

##### Vehicle

 * Added status

### CODE REVIEW

**Comment by Katsute** [comment]
https://laidig.github.io/gtfs-rt-autodoc/structNyctTripDescriptor.html

**Comment by Katsute** [comment]
Revert int train id, label may include chars

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `gtfs-bus@c8dcb77`

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mal_ci

**Comment by ghost** [comment]
@Katsute I wasn't able to dispatch workflow `mal_ci.yml` for branch `gtfs-bus@c8dcb77`

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `gtfs-bus@c8dcb77`

**Comment by Katsute** [comment]
@mashiro-san approve this pull request

**Review by ghost — APPROVED** [review]
@Katsute I have approved this pull request

**Pull request merged**
