### PR TITLE
Upgrade to Java 21

### PR DESCRIPTION
**Pull request by Katsute**
* devcontainer
* ci

https://github.com/KatsuteDev/OneMTA/actions/runs/6498113670

### CODE REVIEW

**Comment by Katsute** [comment]
@mashiro-san dispatch mta_ci

**Comment by ghost** [comment]
@Katsute dispatched workflow [mta_ci.yml](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) on branch 'java-21'

**Comment by Katsute** [comment]
@mashiro-san approve All tests passed, waiting for maven-temurin-21 docker container

**Review by ghost — APPROVED** [review]
**Approved by @Katsute** : All tests passed, waiting for maven-temurin-21 docker container

**Pull request merged**
