### PR TITLE
Fix express routes using unknown feed

### LINKED ISSUE #96: Failing to `resolveSubwayFeed` on express routes
Missing `~X` routes

https://github.com/KatsuteDev/OneMTA/blob/ebf9c8e44cda6c8a9601d51d648d4e56f124c9d8/src/main/java/dev/katsute/onemta/MTAImpl.java#L115-L154

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Fix #96 
 - Strip express from feed request

[WF-3257766740](https://github.com/KatsuteDev/OneMTA/actions/runs/3257766740)

### CODE REVIEW

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `fix-express@2497bb1`

**Comment by Katsute** [comment]
@mashiro-san approve this pull

**Review by ghost — APPROVED** [review]
@Katsute I have approved this pull request

**Pull request merged**
