### PR TITLE
Add method to check if subway train is running express

### LINKED ISSUE #29: Add method to check if subway is express
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

Add method to subway vehicles to check if they are express.

Achieved by checking the route ID of the trip, express routes will end with an `x`.

Local example: `7`
Express example: `7X`

### Reason

Subway express statuses are a commonly requested field

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*If checks are not passed then the pull request will be closed.*

 - [x] I have checked that no other similar pull request already exists.
 - [x] My code follows the general code style as the rest of the code.
 - [x] I have checked that no sensitive information is exposed.
 - [x] Build compiles.
 - [x] Build passes test cases.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Implement #29

### CODE REVIEW

**Comment by Katsute** [comment]
Needs to be tested during express hours before pull can be merged

**Comment by Katsute** [comment]
Passes remote tests, needs to be tested locally

**Comment by Katsute** [comment]
@sinon-bot approve tested locally

**Review by ghost — APPROVED** [review]
> tested locally

<sub>This pull was approved by @Katsute.</sub>

**Pull request merged**
