### PR TITLE
Add canceled trip

### LINKED ISSUE #51: Cancelled Trip API
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] I have checked [discussions](https://github.com/KatsuteDev/OneMTA/discussions).
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

The MTA SIRI Bus API has received an update: https://bustime.mta.info/wiki/Developers/CancelledTripAPIFeatures

||Without Cancelled Trip Information|With Cancelled Trip Information|
|:-:|:-:|:-:|
|v1|`/api/siri/stop-monitoring.xml`|`/api/2/siri/stop-monitoring.xml`|
|v2|`/api/siri/stop-monitoring.xml?version=2`|`/api/2/siri/stop-monitoring.xml?version=2`|

### Stop-monitoring output

```diff
<MonitoredVehicleJourney>
  <MonitoredStopVisit>
--    <MonitoredCall>
--      <ArrivalStatus>cancelled</ArrivalStatus>
--      <DepartureStatus>cancelled</DepartureStatus>
--    </MonitoredCall>
++  <MonitoredVehicleJourney>
++      <VehicleStatus>cancelled</VehicleStatus>
++  </MonitoredVehicleJourney>
  </MonitoredStopVisit>
</MonitoredVehicleJourney>
```

### Alert Support

```gtfs
 entity {
  id: "MTA NYCT_GH_A2-Weekday-SDon-063200_BX39_765"
  alert {
    informed_entity {
      agency_id: "MTA NYCT"
      trip {
        route_id: "BX39"
        direction_id: 0
      }
    }
    informed_entity {
      agency_id: "MTA NYCT"
      trip {
        route_id: "BX39"
        direction_id: 1
      }
    }
    effect: REDUCED_SERVICE
    description_text {
      translation {
        text: "The 10:32am BX39 to SOUNDVIEW AV/CORNELL AV is canceled"
        language: "EN"
      }
    }
  }
}
```

### Reason

Required to keep up to date with API.

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*If checks are not passed then the pull request will be closed.*

 - [x] I have checked that no other similar pull request already exists.
 - [x] My code follows the general code style as the rest of the code.
 - [x] I have checked that no sensitive information is exposed.
 - [x] Build compiles.
 - [x] Build passes test cases.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Added trip alert effect
 - Added trip schedule relationship

https://github.com/KatsuteDev/OneMTA/actions/runs/2456206932

### CODE REVIEW

**Comment by Katsute** [comment]
@sinon-bot sync

**Comment by Katsute** [comment]
@sinon-bot dispatch mal_ci

**Comment by ghost** [comment]
#### ⛔ Error

Failed to dispatch `mal_ci.yml` on branch `canceled@f42fd05`

**Comment by Katsute** [comment]
@sinon-bot dispatch mta_ci

**Comment by ghost** [comment]
#### 🚀 Dispatched Workflow

Dispatched workflow `mta_ci.yml` on branch `canceled@f42fd05`

<sub>This workflow was dispatched by @Katsute.</sub>

**Pull request merged**
