### PR TITLE
Optimize static data

### LINKED ISSUE #89: Optimize data resource + CSV searches
### Feature

When parsed, sort the list by keys; when requesting use a binary search.

### Reason

Current implementation is inefficient.

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Rename tokens
 - Fix #89 

This optimization provides negligible time savings ~20ms, however this pull removes some inefficiencies caused by list iteration so we will use this method instead.

[WF-3109926157](https://github.com/KatsuteDev/OneMTA/actions/runs/3109926157)

### CODE REVIEW

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `optimize-csv@931e9c0`

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `optimize-csv@931e9c0`

**Comment by Katsute** [comment]
Issue with LIRR failing to find stop with new search algorithm, caused by key not being in the first slot.

~~Comparator for rows method needs to check the key index, not always 0.~~

Binary search can not be used on index other than 0. Check which indexes are used most often and presort them.

Add relevant test cases to CSV.

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `optimize-csv@931e9c0`

**Comment by Katsute** [comment]
@mashiro-san approve this pull

**Review by ghost — APPROVED** [review]
@Katsute I have approved this pull request

**Pull request merged**
