### PR TITLE
Optimize cache

### PR DESCRIPTION
**Pull request by Katsute**
### Prerequisites
*Issues must meet the following criteria:*

 - [x] No similar pull request exists.
 - [x] Code follows the general code style of this project.
 - [x] No sensitive information is exposed.
 - [x] Relevant comments have been added.

### GitHub Copilot Disclaimer
*The use of GitHub Copilot is **strictly prohibited** on this repository.*

 - [x] This pull does not use GitHub Copilot.

### Changes Made
*List any changes made and/or other relevant issues.*

 - Allow parallel reads, thread safe writes
 - Optimize how expiry is stored
 - Store cache in concurrent map

[WF-3257283528](https://github.com/KatsuteDev/OneMTA/actions/runs/3257283528)

#### Release Notes

* Optimize cache GET
* Optimize cache WRITE for multiple threads
* Fix cache expiry not working properly

### CODE REVIEW

**Comment by Katsute** [comment]
@mashiro-san dispatch workflow mta_ci

**Comment by ghost** [comment]
@Katsute I have dispatched the workflow [`mta_ci.yml`](https://github.com/KatsuteDev/OneMTA/actions/workflows/mta_ci.yml) for branch `upgrade-cache@ebf9c8e`

**Comment by Katsute** [comment]
@mashiro-san approve this pull

**Review by ghost — APPROVED** [review]
@Katsute I have approved this pull request

**Pull request merged**
